### ISSUE TITLE
Steps for running

### ISSUE THREAD

**Issue by pochadri** [kamkie/mikro-service-example#1]
hi,
 this is a nice sample for microservices, thanks for putting it together. can you please provide the documentation for running it?

**Comment by kamkie** [comment]
Hi,
I added some basic steps in readme

**Comment by pochadri** [comment]
Services need a password to run can you also provide that info, ofcourse it can changed but to see the full example running without changes please provide the same.

**Comment by kamkie** [comment]
passwords and info about JCE added to redme
