### ISSUE TITLE
can teach me how to config encripting config values

### ISSUE THREAD

**Issue by keryhu** [kamkie/mikro-service-example#3]
hello
 I was attracted by your artwork.
And i want to use the encrypting config values in severe config package like you .

as [https://github.com/kamkie/micro-service-example/blob/master/service-config/src/main/resources/application.yml](url) in your server-config module --

> security:
>   user:
>     password: "{cipher}AQBagZV6VJBR3tuScIAuUrnsMPh0hIMxy1qG326pU1PeWv8Bc+R8QexXUqbs9xFORaSPsrzOYkzg3mps8T75LiT9faJEWzorGw1/yTGYMZCm/mAp09MLxQ1JWcMLBDg7+rPPkFGjsSRNRKmloNw5mziq/q00b5+XyJ7Kn0/2SWGk9/JmN5tTeeIC0faCzLMvWIEHgz1ohTJQVp/Kpo26qoeLuQZIE6VvrGfqx+2+rC6BzR6zUL9/5Ol1t76T91eBoUzgI9CYhLeBte+SfppyCBMAp/dEKq55x+4YM0jvMazBKPTlQmWcQd4CIxkSJ+1v3urPvwFP/KQW2RLN9SI/Ehu1CVpyt/kHhVCUpYmRYGgr+ObEAKL61TtlWyzCR/8Qce8="

and yours --

> encrypt:
>   failOnError: false
>   keyStore:
>     location: classpath:key_store.jks
>     password: ${KEY_STORE_PASSWORD:devops}
>     alias: devops

I have followed JCE downolad and JCE installation instruction ,config the right classPath and set a new keyStore 
My question is --
1. How can i translate my password "123456" to "{cipher}encrypted password" like yours by RSA keyStore.
2. And How translate reversed the password from "{cipher} encrypted password" ? what is the decrypt "key"?

Thanks ! 
Can help me?

**Comment by kamkie** [comment]
hi

my service-config is implemented by spring-cloud-config-server
full dosc for it http://cloud.spring.io/spring-cloud-config/spring-cloud-config.html#_encryption_and_decryption

the simplest way is to do this in two steps
- start service with all plain text properties and your desired certificate and use rest endpoint to encrypt values

```
$ curl localhost:8888/encrypt -d mysecret
682bc583f4641835fa2db009355293665d2647dade3375c0ee201de2a49f7bda
```
- put encrypted values in config file and restart application

**Comment by keryhu** [comment]
yes,thanks !
 i follow your suggests , and it works .
but a new error appears , i write in 
http://stackoverflow.com/questions/35122487/spring-cloud-config-server-encryption-by-rsa-keystore-errorsno-decryption-for

can you have some help ?

**Comment by keryhu** [comment]
yes,thanks!
 it works !
